### ISSUE TITLE
Add preview model choice in collection

### ISSUE THREAD

**Issue by ksuquix** [Floppy/van_dam#1114] opened 2023-03-16 13:02 UTC
Floppy: This is probably a "next PR" type thing, but being able to choose the preview model (in the same way you can choose a preview file for a model) would be awesome.

ksuquix: Going a step further, being able to do the choice and/or set it's own image completely might be good (same with creator).

**Comment by Floppy** [comment] 2023-03-16 21:43
duplicate of #1105?

**Comment by Floppy** [comment] 2023-03-16 21:44
this one has more, I'll close the other.

**Closed by Floppy** 2023-03-16 21:43 UTC
Labels: enhancement

**Comment by Floppy** [comment] 2026-04-25 10:26
Duplicated by #5381, so I'll close this one, but the work continues over there :)
