### ISSUE TITLE
QOL - Tweak 03 - User management

### ISSUE THREAD

**Issue by slitzer** [Floppy/van_dam#1366] opened 2023-07-22 09:13 UTC
I see there is an option to create new users in the advanced admin side, however I get an error when trying to create another user

even just a user/admin type role with no option to delete - this would be usefull  to give out logins to my friends without fear of them deleting my files

Not sure if this would fall under this one, but also maybe a TAG associated with that user for Favorites / To Print / Queue

**Comment by Floppy** [comment] 2023-07-29 11:39
Duplicate of #647 :+1:

**Closed by Floppy** 2023-07-29 11:39 UTC
