### ISSUE TITLE
Getting lots of "destination exists" problems after organise

### ISSUE THREAD

**Issue by Floppy** [Floppy/van_dam#1089] opened 2023-03-11 10:59 UTC
I changed my template format, organised some models, and now they are flagged as "destination exists". As far as I can tell, in the "organise" preview dialog, the paths are identical. @ksuquix I think you mentioned something about this?

**Comment by Floppy** [comment] 2023-03-14 11:44
Is this related to #1060 ?

**Comment by ksuquix** [comment] 2023-03-14 14:12
Duplicate of #1059

**Closed by ksuquix** 2023-03-14 14:12 UTC
Labels: bug
